/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'streetwear' : IDL.Null,
  'collab' : IDL.Null,
  'old_money' : IDL.Null,
});
export const Collection = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'itemsCount' : IDL.Nat,
  'category' : Category,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'collectionId' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'price' : IDL.Text,
});
export const BrandInfo = IDL.Record({
  'tagline' : IDL.Text,
  'established' : IDL.Nat,
  'story' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCollection' : IDL.Func(
      [IDL.Text, IDL.Text, Category, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'getAllCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBrandInfo' : IDL.Func([], [BrandInfo], ['query']),
  'setBrandInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'streetwear' : IDL.Null,
    'collab' : IDL.Null,
    'old_money' : IDL.Null,
  });
  const Collection = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'itemsCount' : IDL.Nat,
    'category' : Category,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'collectionId' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'price' : IDL.Text,
  });
  const BrandInfo = IDL.Record({
    'tagline' : IDL.Text,
    'established' : IDL.Nat,
    'story' : IDL.Text,
  });
  
  return IDL.Service({
    'addCollection' : IDL.Func(
        [IDL.Text, IDL.Text, Category, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'getAllCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBrandInfo' : IDL.Func([], [BrandInfo], ['query']),
    'setBrandInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };