/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrandInfo {
  'tagline' : string,
  'established' : bigint,
  'story' : string,
}
export type Category = { 'streetwear' : null } |
  { 'collab' : null } |
  { 'old_money' : null };
export interface Collection {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isFeatured' : boolean,
  'itemsCount' : bigint,
  'category' : Category,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Product {
  'id' : bigint,
  'collectionId' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'price' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addCollection' : ActorMethod<
    [string, string, Category, bigint, boolean],
    bigint
  >,
  'addProduct' : ActorMethod<[string, string, bigint, string, boolean], bigint>,
  'getAllCollections' : ActorMethod<[], Array<Collection>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBrandInfo' : ActorMethod<[], BrandInfo>,
  'setBrandInfo' : ActorMethod<[string, string, bigint], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];