/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BrandInfo {
    tagline: string;
    established: bigint;
    story: string;
}
export type Time = bigint;
export interface Collection {
    id: bigint;
    name: string;
    description: string;
    isFeatured: boolean;
    itemsCount: bigint;
    category: Category;
}
export interface ContactSubmission {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface Product {
    id: bigint;
    collectionId: bigint;
    name: string;
    isAvailable: boolean;
    description: string;
    price: string;
}
export enum Category {
    streetwear = "streetwear",
    collab = "collab",
    old_money = "old_money"
}
export interface backendInterface {
    addCollection(name: string, description: string, category: Category, itemsCount: bigint, isFeatured: boolean): Promise<bigint>;
    addProduct(name: string, price: string, collectionId: bigint, description: string, isAvailable: boolean): Promise<bigint>;
    getAllCollections(): Promise<Array<Collection>>;
    getAllContactSubmissions(): Promise<Array<ContactSubmission>>;
    getAllProducts(): Promise<Array<Product>>;
    getBrandInfo(): Promise<BrandInfo>;
    setBrandInfo(tagline: string, story: string, established: bigint): Promise<void>;
    submitContactForm(name: string, email: string, message: string): Promise<void>;
}
import type { Category as _Category, Collection as _Collection } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCollection(arg0: string, arg1: string, arg2: Category, arg3: bigint, arg4: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCollection(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCollection(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAllCollections(): Promise<Array<Collection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCollections();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCollections();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactSubmissions();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getBrandInfo(): Promise<BrandInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrandInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrandInfo();
            return result;
        }
    }
    async setBrandInfo(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBrandInfo(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBrandInfo(arg0, arg1, arg2);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Collection_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Collection): Collection {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    isFeatured: boolean;
    itemsCount: bigint;
    category: _Category;
}): {
    id: bigint;
    name: string;
    description: string;
    isFeatured: boolean;
    itemsCount: bigint;
    category: Category;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        isFeatured: value.isFeatured,
        itemsCount: value.itemsCount,
        category: from_candid_Category_n6(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    streetwear: null;
} | {
    collab: null;
} | {
    old_money: null;
}): Category {
    return "streetwear" in value ? Category.streetwear : "collab" in value ? Category.collab : "old_money" in value ? Category.old_money : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Collection>): Array<Collection> {
    return value.map((x)=>from_candid_Collection_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    streetwear: null;
} | {
    collab: null;
} | {
    old_money: null;
} {
    return value == Category.streetwear ? {
        streetwear: null
    } : value == Category.collab ? {
        collab: null
    } : value == Category.old_money ? {
        old_money: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
